### ISSUE TITLE
Copywrite vs. Copyright

### ISSUE THREAD

**Issue by lucagubler** [automateyournetwork/automate_your_network#1]
Hi John

Looks like an interesting book and I'm looking forward to reading it!

I noticed on page 3 that you wrote copywrite. I also confused copywrite and copyright the day before yesterday and it was pointed out to me. I also don't know if it matters legally, but maybe you want to correct it :)

https://kathleenwcurry.wordpress.com/2015/07/02/easily-confused-words-copyright-vs-copywrite/

Thanks for publishing the book for free!

Thanks
Luca

**Comment by automateyournetwork** [comment]
Thanks for reaching out - yes unfortunately this error made it to print;
thank you for reminding me of my failure ;)

Appreciate the note - enjoy the book

John
